use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'CXLogger_Example' do
  pod 'CXLogger', :path => '../'

  target 'CXLogger_Tests' do
    inherit! :search_paths

    
  end
end
